import React from 'react'
import './ProfileStatus.css';

const ProfileStatus = () => {

    const showStatusAlert = () => {
        document.getElementById("modal-container").style.display = "block";
        //document.getElementById("container").style.height = "0px";
    }
    const hideStatusAlert = () => {
        document.getElementById("modal-container").style.display = "none";
    }
    
    return (
        <>            
            <div className="profile-status"><button onClick={showStatusAlert}><u>STATUS: (AUTOGENERATED) Active</u></button></div> 
            
            <div id="modal-container" className="status-modal">
              <div id="success-box">
                <div onClick={hideStatusAlert} className="dot"></div>
                <div className="face">
                  <div className="eye"></div>
                  <div className="eye right"></div>
                  <div className="mouth happy"></div>
                </div>
                <div className="shadow scale"></div>
                <div className="status-alert-message">
                  <h1 className="status-alert">YEYYYY!</h1><p>Your profile looks great. Good job!!</p></div>
                <button onClick={hideStatusAlert} className="button-box" ><h1 className="green">Continue</h1></button>
              </div>

              <div id="error-box">
                <div onClick={hideStatusAlert} className="dot"></div>
                <div className="face2">
                  <div className="eye"></div>
                  <div className="eye right"></div>
                  <div className="mouth sad"></div>
                </div>
                <div className="shadow move"></div>
                <div className="status-alert-message">
                  <h1 className="status-alert">UPSY!</h1>
                  <p>It seems like you've missed adding info to your profile. <br></br>Please, complete your registration or you won't be able to work!! </p>
                </div>
                <button onClick={hideStatusAlert} className="button-box"><h1 className="red">Got it!</h1></button>
              </div>
            </div> 
            

        </>
    )
}

export default ProfileStatus